apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: tenant-a
  annotations:
    configsync.gke.io/cluster-name-selector: standalone
spec:
  limits:
  - default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
