---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syncs-repo
  namespace: anthos-third
subjects:
- kind: ServiceAccount
  name: ns-reconciler-anthos-third-rs-a-t-6
  namespace: config-management-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
