apiVersion: v1
kind: Pod
metadata:
  #source: ../../namespaces/anthos-poc/namespace.yaml
  namespace: anthos-poc
  labels:
    app: nginx-privileged
  name: nginx-privileged-allowed
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      privileged: false

